import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "FinCentrix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="text-[#e4e4e0] text-base select-none overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
